services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passs
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: passs
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
